name: PhysicsFlow_good
dependencies:
  - python=3.7
  - pip
  - pip:
    - torch
    - numpy
    - tensorboard
    - setuptools==59.5
    - scipy
    - scikit-learn
    - matplotlib
    - tqdm
    - matplotlib
    - pyDOE
